version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: CarGarage_2025!
      POSTGRES_DB: garage
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
